//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HV2020.Eservice.Klient.MVC.FelanmalanServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSender", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class DataSender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[] adresserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[] granskadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.OrtData[] orterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTypData[] personTyperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData[] personerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[] synpunkterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[] telefonerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData[] verksamheterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[] adresser {
            get {
                return this.adresserField;
            }
            set {
                if ((object.ReferenceEquals(this.adresserField, value) != true)) {
                    this.adresserField = value;
                    this.RaisePropertyChanged("adresser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[] granskade {
            get {
                return this.granskadeField;
            }
            set {
                if ((object.ReferenceEquals(this.granskadeField, value) != true)) {
                    this.granskadeField = value;
                    this.RaisePropertyChanged("granskade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.OrtData[] orter {
            get {
                return this.orterField;
            }
            set {
                if ((object.ReferenceEquals(this.orterField, value) != true)) {
                    this.orterField = value;
                    this.RaisePropertyChanged("orter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTypData[] personTyper {
            get {
                return this.personTyperField;
            }
            set {
                if ((object.ReferenceEquals(this.personTyperField, value) != true)) {
                    this.personTyperField = value;
                    this.RaisePropertyChanged("personTyper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData[] personer {
            get {
                return this.personerField;
            }
            set {
                if ((object.ReferenceEquals(this.personerField, value) != true)) {
                    this.personerField = value;
                    this.RaisePropertyChanged("personer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[] synpunkter {
            get {
                return this.synpunkterField;
            }
            set {
                if ((object.ReferenceEquals(this.synpunkterField, value) != true)) {
                    this.synpunkterField = value;
                    this.RaisePropertyChanged("synpunkter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[] telefoner {
            get {
                return this.telefonerField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonerField, value) != true)) {
                    this.telefonerField = value;
                    this.RaisePropertyChanged("telefoner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData[] verksamheter {
            get {
                return this.verksamheterField;
            }
            set {
                if ((object.ReferenceEquals(this.verksamheterField, value) != true)) {
                    this.verksamheterField = value;
                    this.RaisePropertyChanged("verksamheter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdressData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class AdressData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Ort OrtDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person PersonDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gata {
            get {
                return this.GataField;
            }
            set {
                if ((object.ReferenceEquals(this.GataField, value) != true)) {
                    this.GataField = value;
                    this.RaisePropertyChanged("Gata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Ort OrtData {
            get {
                return this.OrtDataField;
            }
            set {
                if ((object.ReferenceEquals(this.OrtDataField, value) != true)) {
                    this.OrtDataField = value;
                    this.RaisePropertyChanged("OrtData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person PersonData {
            get {
                return this.PersonDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonDataField, value) != true)) {
                    this.PersonDataField = value;
                    this.RaisePropertyChanged("PersonData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postnummer {
            get {
                return this.PostnummerField;
            }
            set {
                if ((this.PostnummerField.Equals(value) != true)) {
                    this.PostnummerField = value;
                    this.RaisePropertyChanged("Postnummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GranskadData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class GranskadData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumGranskadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DokumentNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData SynpunktDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SynpunktIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumGranskad {
            get {
                return this.DatumGranskadField;
            }
            set {
                if ((this.DatumGranskadField.Equals(value) != true)) {
                    this.DatumGranskadField = value;
                    this.RaisePropertyChanged("DatumGranskad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DokumentNr {
            get {
                return this.DokumentNrField;
            }
            set {
                if ((this.DokumentNrField.Equals(value) != true)) {
                    this.DokumentNrField = value;
                    this.RaisePropertyChanged("DokumentNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData SynpunktData {
            get {
                return this.SynpunktDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SynpunktDataField, value) != true)) {
                    this.SynpunktDataField = value;
                    this.RaisePropertyChanged("SynpunktData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SynpunktID {
            get {
                return this.SynpunktIDField;
            }
            set {
                if ((this.SynpunktIDField.Equals(value) != true)) {
                    this.SynpunktIDField = value;
                    this.RaisePropertyChanged("SynpunktID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrtData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class OrtData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData AdressDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData AdressData {
            get {
                return this.AdressDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressDataField, value) != true)) {
                    this.AdressDataField = value;
                    this.RaisePropertyChanged("AdressData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ort {
            get {
                return this.OrtField;
            }
            set {
                if ((object.ReferenceEquals(this.OrtField, value) != true)) {
                    this.OrtField = value;
                    this.RaisePropertyChanged("Ort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postnummer {
            get {
                return this.PostnummerField;
            }
            set {
                if ((this.PostnummerField.Equals(value) != true)) {
                    this.PostnummerField = value;
                    this.RaisePropertyChanged("Postnummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonTypData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class PersonTypData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData PersonDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PersonTypField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData PersonData {
            get {
                return this.PersonDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonDataField, value) != true)) {
                    this.PersonDataField = value;
                    this.RaisePropertyChanged("PersonData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonTyp {
            get {
                return this.PersonTypField;
            }
            set {
                if ((this.PersonTypField.Equals(value) != true)) {
                    this.PersonTypField = value;
                    this.RaisePropertyChanged("PersonTyp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class PersonData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[] AdressererField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTyp PersonTypField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[] SynpunkterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[] TelefonerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[] Adresserer {
            get {
                return this.AdressererField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressererField, value) != true)) {
                    this.AdressererField = value;
                    this.RaisePropertyChanged("Adresserer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Epost {
            get {
                return this.EpostField;
            }
            set {
                if ((object.ReferenceEquals(this.EpostField, value) != true)) {
                    this.EpostField = value;
                    this.RaisePropertyChanged("Epost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTyp PersonTyp {
            get {
                return this.PersonTypField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTypField, value) != true)) {
                    this.PersonTypField = value;
                    this.RaisePropertyChanged("PersonTyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[] Synpunkter {
            get {
                return this.SynpunkterField;
            }
            set {
                if ((object.ReferenceEquals(this.SynpunkterField, value) != true)) {
                    this.SynpunkterField = value;
                    this.RaisePropertyChanged("Synpunkter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[] Telefoner {
            get {
                return this.TelefonerField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonerField, value) != true)) {
                    this.TelefonerField = value;
                    this.RaisePropertyChanged("Telefoner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynpunktData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class SynpunktData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AvseendeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumMottagitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnhetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[] GranskadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData PersonDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynpunkTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SynpunktIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData verksamhetDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Avseende {
            get {
                return this.AvseendeField;
            }
            set {
                if ((this.AvseendeField.Equals(value) != true)) {
                    this.AvseendeField = value;
                    this.RaisePropertyChanged("Avseende");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumMottagit {
            get {
                return this.DatumMottagitField;
            }
            set {
                if ((this.DatumMottagitField.Equals(value) != true)) {
                    this.DatumMottagitField = value;
                    this.RaisePropertyChanged("DatumMottagit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enhet {
            get {
                return this.EnhetField;
            }
            set {
                if ((object.ReferenceEquals(this.EnhetField, value) != true)) {
                    this.EnhetField = value;
                    this.RaisePropertyChanged("Enhet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[] Granskad {
            get {
                return this.GranskadField;
            }
            set {
                if ((object.ReferenceEquals(this.GranskadField, value) != true)) {
                    this.GranskadField = value;
                    this.RaisePropertyChanged("Granskad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData PersonData {
            get {
                return this.PersonDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonDataField, value) != true)) {
                    this.PersonDataField = value;
                    this.RaisePropertyChanged("PersonData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynpunkText {
            get {
                return this.SynpunkTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SynpunkTextField, value) != true)) {
                    this.SynpunkTextField = value;
                    this.RaisePropertyChanged("SynpunkText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SynpunktID {
            get {
                return this.SynpunktIDField;
            }
            set {
                if ((this.SynpunktIDField.Equals(value) != true)) {
                    this.SynpunktIDField = value;
                    this.RaisePropertyChanged("SynpunktID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData verksamhetData {
            get {
                return this.verksamhetDataField;
            }
            set {
                if ((object.ReferenceEquals(this.verksamhetDataField, value) != true)) {
                    this.verksamhetDataField = value;
                    this.RaisePropertyChanged("verksamhetData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefonData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class TelefonData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData persondataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefonnummer {
            get {
                return this.TelefonnummerField;
            }
            set {
                if ((this.TelefonnummerField.Equals(value) != true)) {
                    this.TelefonnummerField = value;
                    this.RaisePropertyChanged("Telefonnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData persondata {
            get {
                return this.persondataField;
            }
            set {
                if ((object.ReferenceEquals(this.persondataField, value) != true)) {
                    this.persondataField = value;
                    this.RaisePropertyChanged("persondata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerksamhetData", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class VerksamhetData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnhetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerksamhetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enhet {
            get {
                return this.EnhetField;
            }
            set {
                if ((object.ReferenceEquals(this.EnhetField, value) != true)) {
                    this.EnhetField = value;
                    this.RaisePropertyChanged("Enhet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Verksamhet {
            get {
                return this.VerksamhetField;
            }
            set {
                if ((object.ReferenceEquals(this.VerksamhetField, value) != true)) {
                    this.VerksamhetField = value;
                    this.RaisePropertyChanged("Verksamhet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ort", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class Ort : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Adress AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ort1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Adress Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ort1 {
            get {
                return this.Ort1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Ort1Field, value) != true)) {
                    this.Ort1Field = value;
                    this.RaisePropertyChanged("Ort1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postnummer {
            get {
                return this.PostnummerField;
            }
            set {
                if ((this.PostnummerField.Equals(value) != true)) {
                    this.PostnummerField = value;
                    this.RaisePropertyChanged("Postnummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Adress[] AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTyp PersonTypField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Synpunkt[] SynpunktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Telefon[] TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Adress[] Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Epost {
            get {
                return this.EpostField;
            }
            set {
                if ((object.ReferenceEquals(this.EpostField, value) != true)) {
                    this.EpostField = value;
                    this.RaisePropertyChanged("Epost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTyp PersonTyp {
            get {
                return this.PersonTypField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTypField, value) != true)) {
                    this.PersonTypField = value;
                    this.RaisePropertyChanged("PersonTyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Synpunkt[] Synpunkt {
            get {
                return this.SynpunktField;
            }
            set {
                if ((object.ReferenceEquals(this.SynpunktField, value) != true)) {
                    this.SynpunktField = value;
                    this.RaisePropertyChanged("Synpunkt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Telefon[] Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adress", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class Adress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Ort OrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gata {
            get {
                return this.GataField;
            }
            set {
                if ((object.ReferenceEquals(this.GataField, value) != true)) {
                    this.GataField = value;
                    this.RaisePropertyChanged("Gata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Ort Ort {
            get {
                return this.OrtField;
            }
            set {
                if ((object.ReferenceEquals(this.OrtField, value) != true)) {
                    this.OrtField = value;
                    this.RaisePropertyChanged("Ort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postnummer {
            get {
                return this.PostnummerField;
            }
            set {
                if ((this.PostnummerField.Equals(value) != true)) {
                    this.PostnummerField = value;
                    this.RaisePropertyChanged("Postnummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonTyp", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class PersonTyp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PersonTyp1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonTyp1 {
            get {
                return this.PersonTyp1Field;
            }
            set {
                if ((this.PersonTyp1Field.Equals(value) != true)) {
                    this.PersonTyp1Field = value;
                    this.RaisePropertyChanged("PersonTyp1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Synpunkt", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class Synpunkt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AvseendeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumMottagitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnhetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Granskad[] GranskadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynpunkTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SynpunktIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Avseende {
            get {
                return this.AvseendeField;
            }
            set {
                if ((this.AvseendeField.Equals(value) != true)) {
                    this.AvseendeField = value;
                    this.RaisePropertyChanged("Avseende");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumMottagit {
            get {
                return this.DatumMottagitField;
            }
            set {
                if ((this.DatumMottagitField.Equals(value) != true)) {
                    this.DatumMottagitField = value;
                    this.RaisePropertyChanged("DatumMottagit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enhet {
            get {
                return this.EnhetField;
            }
            set {
                if ((object.ReferenceEquals(this.EnhetField, value) != true)) {
                    this.EnhetField = value;
                    this.RaisePropertyChanged("Enhet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Granskad[] Granskad {
            get {
                return this.GranskadField;
            }
            set {
                if ((object.ReferenceEquals(this.GranskadField, value) != true)) {
                    this.GranskadField = value;
                    this.RaisePropertyChanged("Granskad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynpunkText {
            get {
                return this.SynpunkTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SynpunkTextField, value) != true)) {
                    this.SynpunkTextField = value;
                    this.RaisePropertyChanged("SynpunkText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SynpunktID {
            get {
                return this.SynpunktIDField;
            }
            set {
                if ((this.SynpunktIDField.Equals(value) != true)) {
                    this.SynpunktIDField = value;
                    this.RaisePropertyChanged("SynpunktID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telefon", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class Telefon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonnummerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefonnummer {
            get {
                return this.TelefonnummerField;
            }
            set {
                if ((this.TelefonnummerField.Equals(value) != true)) {
                    this.TelefonnummerField = value;
                    this.RaisePropertyChanged("Telefonnummer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Granskad", Namespace="http://schemas.datacontract.org/2004/07/HV2020.Eservice.WCF.Felanmalan")]
    [System.SerializableAttribute()]
    public partial class Granskad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumGranskadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DokumentNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Synpunkt SynpunktField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SynpunktIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumGranskad {
            get {
                return this.DatumGranskadField;
            }
            set {
                if ((this.DatumGranskadField.Equals(value) != true)) {
                    this.DatumGranskadField = value;
                    this.RaisePropertyChanged("DatumGranskad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DokumentNr {
            get {
                return this.DokumentNrField;
            }
            set {
                if ((this.DokumentNrField.Equals(value) != true)) {
                    this.DokumentNrField = value;
                    this.RaisePropertyChanged("DokumentNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.Synpunkt Synpunkt {
            get {
                return this.SynpunktField;
            }
            set {
                if ((object.ReferenceEquals(this.SynpunktField, value) != true)) {
                    this.SynpunktField = value;
                    this.RaisePropertyChanged("Synpunkt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SynpunktID {
            get {
                return this.SynpunktIDField;
            }
            set {
                if ((this.SynpunktIDField.Equals(value) != true)) {
                    this.SynpunktIDField = value;
                    this.RaisePropertyChanged("SynpunktID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FelanmalanServiceReference.IFelanmalanService")]
    public interface IFelanmalanService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/DataTransfer", ReplyAction="http://tempuri.org/IFelanmalanService/DataTransferResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.DataSender DataTransfer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/DataTransfer", ReplyAction="http://tempuri.org/IFelanmalanService/DataTransferResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.DataSender> DataTransferAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreatePerson", ReplyAction="http://tempuri.org/IFelanmalanService/CreatePersonResponse")]
        void CreatePerson(string epost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreatePerson", ReplyAction="http://tempuri.org/IFelanmalanService/CreatePersonResponse")]
        System.Threading.Tasks.Task CreatePersonAsync(string epost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateTelefon", ReplyAction="http://tempuri.org/IFelanmalanService/CreateTelefonResponse")]
        void CreateTelefon(int telefonnummer, int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateTelefon", ReplyAction="http://tempuri.org/IFelanmalanService/CreateTelefonResponse")]
        System.Threading.Tasks.Task CreateTelefonAsync(int telefonnummer, int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateAdress", ReplyAction="http://tempuri.org/IFelanmalanService/CreateAdressResponse")]
        void CreateAdress(int postnummer, string gata, int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateAdress", ReplyAction="http://tempuri.org/IFelanmalanService/CreateAdressResponse")]
        System.Threading.Tasks.Task CreateAdressAsync(int postnummer, string gata, int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateOrt", ReplyAction="http://tempuri.org/IFelanmalanService/CreateOrtResponse")]
        void CreateOrt(int postnummer, string ort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateOrt", ReplyAction="http://tempuri.org/IFelanmalanService/CreateOrtResponse")]
        System.Threading.Tasks.Task CreateOrtAsync(int postnummer, string ort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreatePersonTyp", ReplyAction="http://tempuri.org/IFelanmalanService/CreatePersonTypResponse")]
        void CreatePersonTyp(int personID, bool personTyp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreatePersonTyp", ReplyAction="http://tempuri.org/IFelanmalanService/CreatePersonTypResponse")]
        System.Threading.Tasks.Task CreatePersonTypAsync(int personID, bool personTyp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateSynpunkt", ReplyAction="http://tempuri.org/IFelanmalanService/CreateSynpunktResponse")]
        void CreateSynpunkt(string enhet, System.DateTime datumMottagit, string synpunkText, short avseende, int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateSynpunkt", ReplyAction="http://tempuri.org/IFelanmalanService/CreateSynpunktResponse")]
        System.Threading.Tasks.Task CreateSynpunktAsync(string enhet, System.DateTime datumMottagit, string synpunkText, short avseende, int personID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateVerksamhet", ReplyAction="http://tempuri.org/IFelanmalanService/CreateVerksamhetResponse")]
        void CreateVerksamhet(string enhet, string verksamhet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateVerksamhet", ReplyAction="http://tempuri.org/IFelanmalanService/CreateVerksamhetResponse")]
        System.Threading.Tasks.Task CreateVerksamhetAsync(string enhet, string verksamhet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateGranskad", ReplyAction="http://tempuri.org/IFelanmalanService/CreateGranskadResponse")]
        void CreateGranskad(System.Nullable<System.DateTime> datumGranskad, int synpunktID, System.Nullable<int> LoginID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/CreateGranskad", ReplyAction="http://tempuri.org/IFelanmalanService/CreateGranskadResponse")]
        System.Threading.Tasks.Task CreateGranskadAsync(System.Nullable<System.DateTime> datumGranskad, int synpunktID, System.Nullable<int> LoginID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllPerson", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllPersonResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData[] ReadAllPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllPerson", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllPersonResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData[]> ReadAllPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllTelefon", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllTelefonResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[] ReadAllTelefon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllTelefon", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllTelefonResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[]> ReadAllTelefonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllAdress", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllAdressResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[] ReadAllAdress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllAdress", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllAdressResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[]> ReadAllAdressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllOrt", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllOrtResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.OrtData[] ReadAllOrt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllOrt", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllOrtResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.OrtData[]> ReadAllOrtAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllPersonTyp", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllPersonTypResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTypData[] ReadAllPersonTyp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllPersonTyp", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllPersonTypResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTypData[]> ReadAllPersonTypAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllSynpunkt", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllSynpunktResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[] ReadAllSynpunkt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllSynpunkt", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllSynpunktResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[]> ReadAllSynpunktAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllVerksamhet", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllVerksamhetResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData[] ReadAllVerksamhet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllVerksamhet", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllVerksamhetResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData[]> ReadAllVerksamhetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllGranskad", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllGranskadResponse")]
        HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[] ReadAllGranskad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelanmalanService/ReadAllGranskad", ReplyAction="http://tempuri.org/IFelanmalanService/ReadAllGranskadResponse")]
        System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[]> ReadAllGranskadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFelanmalanServiceChannel : HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.IFelanmalanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FelanmalanServiceClient : System.ServiceModel.ClientBase<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.IFelanmalanService>, HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.IFelanmalanService {
        
        public FelanmalanServiceClient() {
        }
        
        public FelanmalanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FelanmalanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FelanmalanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FelanmalanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.DataSender DataTransfer() {
            return base.Channel.DataTransfer();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.DataSender> DataTransferAsync() {
            return base.Channel.DataTransferAsync();
        }
        
        public void CreatePerson(string epost) {
            base.Channel.CreatePerson(epost);
        }
        
        public System.Threading.Tasks.Task CreatePersonAsync(string epost) {
            return base.Channel.CreatePersonAsync(epost);
        }
        
        public void CreateTelefon(int telefonnummer, int personID) {
            base.Channel.CreateTelefon(telefonnummer, personID);
        }
        
        public System.Threading.Tasks.Task CreateTelefonAsync(int telefonnummer, int personID) {
            return base.Channel.CreateTelefonAsync(telefonnummer, personID);
        }
        
        public void CreateAdress(int postnummer, string gata, int personID) {
            base.Channel.CreateAdress(postnummer, gata, personID);
        }
        
        public System.Threading.Tasks.Task CreateAdressAsync(int postnummer, string gata, int personID) {
            return base.Channel.CreateAdressAsync(postnummer, gata, personID);
        }
        
        public void CreateOrt(int postnummer, string ort) {
            base.Channel.CreateOrt(postnummer, ort);
        }
        
        public System.Threading.Tasks.Task CreateOrtAsync(int postnummer, string ort) {
            return base.Channel.CreateOrtAsync(postnummer, ort);
        }
        
        public void CreatePersonTyp(int personID, bool personTyp) {
            base.Channel.CreatePersonTyp(personID, personTyp);
        }
        
        public System.Threading.Tasks.Task CreatePersonTypAsync(int personID, bool personTyp) {
            return base.Channel.CreatePersonTypAsync(personID, personTyp);
        }
        
        public void CreateSynpunkt(string enhet, System.DateTime datumMottagit, string synpunkText, short avseende, int personID) {
            base.Channel.CreateSynpunkt(enhet, datumMottagit, synpunkText, avseende, personID);
        }
        
        public System.Threading.Tasks.Task CreateSynpunktAsync(string enhet, System.DateTime datumMottagit, string synpunkText, short avseende, int personID) {
            return base.Channel.CreateSynpunktAsync(enhet, datumMottagit, synpunkText, avseende, personID);
        }
        
        public void CreateVerksamhet(string enhet, string verksamhet) {
            base.Channel.CreateVerksamhet(enhet, verksamhet);
        }
        
        public System.Threading.Tasks.Task CreateVerksamhetAsync(string enhet, string verksamhet) {
            return base.Channel.CreateVerksamhetAsync(enhet, verksamhet);
        }
        
        public void CreateGranskad(System.Nullable<System.DateTime> datumGranskad, int synpunktID, System.Nullable<int> LoginID) {
            base.Channel.CreateGranskad(datumGranskad, synpunktID, LoginID);
        }
        
        public System.Threading.Tasks.Task CreateGranskadAsync(System.Nullable<System.DateTime> datumGranskad, int synpunktID, System.Nullable<int> LoginID) {
            return base.Channel.CreateGranskadAsync(datumGranskad, synpunktID, LoginID);
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData[] ReadAllPerson() {
            return base.Channel.ReadAllPerson();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonData[]> ReadAllPersonAsync() {
            return base.Channel.ReadAllPersonAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[] ReadAllTelefon() {
            return base.Channel.ReadAllTelefon();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.TelefonData[]> ReadAllTelefonAsync() {
            return base.Channel.ReadAllTelefonAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[] ReadAllAdress() {
            return base.Channel.ReadAllAdress();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.AdressData[]> ReadAllAdressAsync() {
            return base.Channel.ReadAllAdressAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.OrtData[] ReadAllOrt() {
            return base.Channel.ReadAllOrt();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.OrtData[]> ReadAllOrtAsync() {
            return base.Channel.ReadAllOrtAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTypData[] ReadAllPersonTyp() {
            return base.Channel.ReadAllPersonTyp();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.PersonTypData[]> ReadAllPersonTypAsync() {
            return base.Channel.ReadAllPersonTypAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[] ReadAllSynpunkt() {
            return base.Channel.ReadAllSynpunkt();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.SynpunktData[]> ReadAllSynpunktAsync() {
            return base.Channel.ReadAllSynpunktAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData[] ReadAllVerksamhet() {
            return base.Channel.ReadAllVerksamhet();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.VerksamhetData[]> ReadAllVerksamhetAsync() {
            return base.Channel.ReadAllVerksamhetAsync();
        }
        
        public HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[] ReadAllGranskad() {
            return base.Channel.ReadAllGranskad();
        }
        
        public System.Threading.Tasks.Task<HV2020.Eservice.Klient.MVC.FelanmalanServiceReference.GranskadData[]> ReadAllGranskadAsync() {
            return base.Channel.ReadAllGranskadAsync();
        }
    }
}
